#!/bin/bash
set -euo pipefail
export PROMPT_DATA=${PROMPT_DATA:-$VERL_DATA/slime_drug_agent_data/toolrl/mcp_sft_all.toolrl_steps.jsonl}
export ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE:-2}
DATASET_SIZE=$(wc -l < "$PROMPT_DATA")
export NUM_ROLLOUT=${NUM_ROLLOUT:-$(((DATASET_SIZE + ROLLOUT_BATCH_SIZE - 1) / ROLLOUT_BATCH_SIZE))}
export N_SAMPLES_PER_PROMPT=${N_SAMPLES_PER_PROMPT:-2}
export GLOBAL_BATCH_SIZE=${GLOBAL_BATCH_SIZE:-4}
export ROLLOUT_MAX_PROMPT_LEN=${ROLLOUT_MAX_PROMPT_LEN:-6144}
export ROLLOUT_MAX_RESPONSE_LEN=${ROLLOUT_MAX_RESPONSE_LEN:-512}
export ROLLOUT_MAX_CONTEXT_LEN=${ROLLOUT_MAX_CONTEXT_LEN:-6656}
export MAX_TOKENS_PER_GPU=${MAX_TOKENS_PER_GPU:-4096}
export SAVE_INTERVAL=${SAVE_INTERVAL:-20}
echo "[4B OPD full] dataset_size=$DATASET_SIZE prompt_batches=$NUM_ROLLOUT"
exec bash drug_agent/opd/scripts/run_qwen3_5_4b_opd.sh
